[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@ccip/=lib/ccip/',
    '@chainlink/local/=lib/chainlink-local/',
]
# RPC endpoints belong in their own table
[rpc_endpoints]
sepolia-eth = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"